### ISSUE TITLE
Support for Sql Azure

### ISSUE THREAD

**Issue by ynauls** [brunomlopes/dbdeploy.net#10]
Thank you for the awesome work,  by an chance, is there a possibility of merging this project with  "https://dbdeploynet2.codeplex.com/"?

**Comment by brunomlopes** [comment]
Thanks.
I think that project is built up from scratch and not based on this at all, so any merge would probably be hard to very hard, since it's two different codebases.

**Comment by ynauls** [comment]
thank you for the reply @brunomlopes, makes sense.
