### ISSUE TITLE
Intallation instructions?

### ISSUE THREAD

**Issue by git4t** [brunomlopes/dbdeploy.net#17]
Could you please update the readme file with installation instructions.? 

I downloaded and installed the nuget package of this tool. After installing the .nupkg file to my .net project, I do not see any folders or files relevant to your tool created in the solution/project. 

Am i supposed to write code in order for making this work after installing the nuget package.? 

Over all, it is not so clear how to install and use your tool. Kindly request to address the gaps and publish more clearer instructions please. 

thanks.

**Comment by brunomlopes** [comment]
The nuget package just contains tools.

There are the following runners:
- console (an exec)
- powershell  (a dll containing cmdlets)
- msbuild (a dll containing msbuild tasks)
- nant (a dll containing nant tasks)

You can pick which runner is better for you and use that.

**Comment by git4t** [comment]
Ok. thank you for the prompt response.
