### ISSUE TITLE
Just output the script

### ISSUE THREAD

**Issue by git4t** [brunomlopes/dbdeploy.net#18]
Hi, 

I need only the sql script as output and "do not" need the script run on the database. what settings should i use? 

thanks.

**Comment by brunomlopes** [comment]
Hi,

Using the console runner, you can use "outputfile" and it will write the delta into the specified file. See [here](https://github.com/brunomlopes/dbdeploy.net/blob/master/src/Dbdeploy.Console/OptionsManager.cs#L103)

**Comment by git4t** [comment]
Ok. thank you for the prompt response.
